language: rust
os:
  - linux
  - osx
sudo: false

addons:
  apt:
    packages:
      - cmake
      - ninja-build

rust:
  - stable

before_install:
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja; fi

script:
  - cargo build
  - cargo test -- "tests::"