language: rust
rust:
  - stable

os:
  - linux
  - osx

sudo: required
addons:
  apt:
    packages:
      # To build nng
      #- cmake
      - ninja-build
      # To build kcov
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - gcc
      - binutils-dev
      - libiberty-dev

before_install:
  # Using `source` so can update PATH environment variable
  - source ./scripts/install.sh
  - cmake --version

script:
  - cargo build
  - cargo test -- "tests::"

after_success:
  - ./scripts/after_success.sh