# Based off https://github.com/starkat99/appveyor-rust

image: 
- Visual Studio 2017
- Ubuntu

for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  environment:
    matrix:
      # Stable 64-bit MSVC
      - channel: stable
        target: x86_64-pc-windows-msvc
      # Stable 32-bit MSVC
      - channel: stable
        target: i686-pc-windows-msvc
  install:
    # Download rustup and install rust
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init -yv --default-toolchain %channel% --default-host %target%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    # Install ninja (used to build nng)
    - choco install ninja

for:
-
  matrix:
    only:
      - image: Ubuntu
  install:
    - sudo apt-get update
    - sudo apt-get install cmake ninja-build
    # Download and run rustup to install Rust
    - curl https://sh.rustup.rs -sSf | sh
  

install:
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cargo test --verbose

# after_test:
#   - cmd: codecov -f "coverage.xml" -t 2a07cd3d-8620-4495-8c14-3252b10b90bd
