# Based off https://github.com/starkat99/appveyor-rust

image: 
- Visual Studio 2017

environment:
  matrix:
    # Stable 64-bit MSVC
    - target: x86_64-pc-windows-msvc
      channel: stable
    # Stable 32-bit MSVC
    - target: i686-pc-windows-msvc
      channel: stable

install:
  # Download rustup and install rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  # Install ninja (used to build nng)
  - choco install ninja
  - rustc -vV
  - cargo -vV

# Skip build step since `cargo test` does it
build: false

test_script:
  # Run only our tests (not tests in dependencies)
  - cargo test --verbose -- "tests::"