[package]
name = "runng-thrift"
version = "0.1.0"
authors = ["Jake <jeikabu+github@gmail.com>"]

[dependencies]
runng = { version = "0.1.1", path = "../runng" }
thrift = { version = "1.0.0", path = "../../../thrift/lib/rs" }
try_from = "0.2"
ordered-float = "1.0"